Proposal for probeye's first version
BAMresearch/probeye pull request #1
Opened 2021-08-19 12:20 UTC by aklawonn

As the title suggests, this is a proposal for the initial version of probeye. The pull request should give all contributors the chance to look on the code, and comment on what they would like to change before the merge into the main-branch.

2021-08-23 11:57 UTC, joergfunger requested changes
In the first review, I did not have time to look into the test cases. But I guess with the changes tey might change as well. In general, this is a very promising first version, in particular the documentation is very nice.

2021-08-23 11:57 UTC, joergfunger commented on probeye/forward_model.py
> +        exp_inp : dict
As mentioned above, I would call that data that then includes deterministic as well as measured quantities.

2021-08-23 11:57 UTC, joergfunger commented on probeye/forward_model.py
> +        response_dict = {output_sensor.name: self.response(inp, output_sensor)
I would require the user to implement this function (instead of having a response function).

2021-08-23 11:57 UTC, joergfunger commented on probeye/forward_model.py
> +    def error_function(self, exp_inp, prms, output_sensor, ye):
this could be  done by the metric_function at the sensor.

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +        self._prior_classes = {'normal': PriorNormal,
What is the advantage of using a string vs directly specififying a base class that can then be directly added by the user (without changing the library code)?

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +        """Provides n_calibration_prms attribute."""
What's the difference, is the first one the deterministic + latent, whereas the second is only the latent ones?

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +            Either 'model' (for a model parameter), 'prior' (for a prior
this is not fully clear to me. Why shouldn't I define a hyperparameter of the prior not via this definition? I would have thought to first define the hyper prior, and then use that variable as a definition for the model parameter prior. So from my point of view, variables are either model, prior or noise (X0, X1, X2) or constant.

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +            If the added parameter is a 'calibration'-parameter, this argument
calibration parameter = latent variable?

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +            prior_type = prior[0]  # e.g. 'normal', 'lognormal', etc.
As mentioned above, I feel like a class would be better here. Then everyone can directly define the parameters of the prior (so Gamma might have alpha, and normal mu and sigma).

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +    def change_parameter_role(self, prm_name, const=None, prior=None,
For me, the need for this method is rather unclear. I would directly define that in the definition, and potentially having to define the outer variables first. (So first define the hyperparameters prior, and then define the model parameters prior with parameters that are already latent variables).

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +        self._noise_models[output_sensor_name] = noise_model
The noise model does not necessarily relate to the sensor (e.g. if you have a correlated noise model with stereo camera data and laser measuring the same thing, thus are correlated),you would have to define a "joint" noise model.

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +    def logprior(self, theta):
those functions should be moved to the inference, since the computation (e.g.the evaluation of the likehood or prior) is done there.

2021-08-23 11:57 UTC, joergfunger commented on probeye/inference_problem.py
> +    def sample_from_prior(self, prm_name, size):
see above

2021-08-23 11:57 UTC, joergfunger commented on probeye/noise.py
> +    def loglike_contribution(self, model_error_vector, prms):
it is not necessarily the model error, but the output of the sensor_metric function.

2021-08-23 11:57 UTC, joergfunger commented on probeye/parameter.py
> +    The main parameter 'library'. In this dictionary, all of the problem's
Should we consider extending this to vector parameters?

2021-08-23 11:57 UTC, joergfunger commented on probeye/parameter.py
> +        self.index = prm_dict['index']
for vector parameters, we would add the length

2021-08-23 11:57 UTC, joergfunger commented on probeye/priors.py
> +    this class is defined is to avoid storing any numeric values for any of the
delete is defined

2021-08-23 11:57 UTC, joergfunger commented on probeye/priors.py
> +    def generate_samples(self, prms, size, seed=None):
is that something that is a description of the inference problem or that is a helper function in the inerence? From my point of view, this is the latter and then might be moved there.

2021-08-23 11:57 UTC, joergfunger commented on probeye/solver.py
> +def taralli_solver(problem, n_walkers=20, n_steps=1000, plot=True,
move this solver to a subdirectory solver/taralli

2021-08-23 14:09 UTC, aklawonn commented on examples/example_linear_regression.py
> +problem.add_noise_model(out_1.name, NormalNoiseZeroMean(['sigma']))
'sigma' is supposed to be identified here. This can be checked by looking at the definition of 'sigma' when it was added to the problem. Since it is not a constant (it was assigned a prior) it will be inferred.

2021-08-23 14:13 UTC, aklawonn commented on probeye/parameter.py
> +    The main parameter 'library'. In this dictionary, all of the problem's
We can do that, but I guess it would require changes at several locations in the code. I would suggest to add this change after we have published the initial version, since it is IMO more of a special case when you have vector-type parameters.

2021-08-23 14:14 UTC, aklawonn commented on probeye/parameter.py
> +        self.index = prm_dict['index']
Yes, for that case, we would need to add a length-attribute. As suggested before, I would implement that change, after publishing the initial version, if you don't mind.

2021-08-24 06:18 UTC, aklawonn commented on examples/example_linear_regression.py
> +problem.add_parameter('a', 'model',
I added more explanations to the code in the linear regression example. I will add it with the next push to this branch.

2021-08-24 06:19 UTC, aklawonn commented on examples/example_linear_regression.py
> +                          LinearModel([{'a': 'm'}, 'b'], [inp_1], [out_1]))
Yes indeed. I added some comments on that. Will be added with the next push.

2021-08-24 06:33 UTC, aklawonn commented on examples/example_linear_regression.py
> +problem.add_experiment(f'TestSeries_1', sensors={'x': x_test, 'y': y_test},
I like the term sensor in this context, because it mirrors the setup of the forward model. If you have a sensor with name 'x' in the forward model, there has to be a sensor called 'x' in the experiment (and the noise model will take these two sensors, and compare them). I think this concept is the easiest to grasp, when both data containers are called 'sensor'. I can see, that the term data would be appealing in that sense, that it is more neutral, but I would think the mirror-concept is more valuable to have.

2021-08-24 06:34 UTC, aklawonn commented on examples/example_linear_regression.py
> +taralli_solver(problem, n_walkers=n_walkers, n_steps=n_steps)
Maybe you just looked on the code in your browser, because if you run this example, some post-processing is happening, and two plots are created.

2021-08-24 06:41 UTC, aklawonn commented on examples/example_multiple_sensors.py
> +class PositionSensor(OutputSensor):
I would argue, that any numeric datum in the experiments is provided by some sensor, because it was measured in one way or the other. so there is only sensors. but in the forward model, which mirrors some sensors of the experiments, some of those sensors are interpreted as input and some as output. simply because the forward model is a function with a domain (input) and an image (output). I would not say, that every sensor is an output sensor.

2021-08-24 06:45 UTC, aklawonn commented on examples/example_multiple_sensors.py
> +inp_1 = InputSensor("time")
The latter (i.e. specify the time steps as a bunch of parameters, or at least prepare the possibility to do so) is IMO too confusing for a simple example. Regarding the sensors, maybe we should have a discussion on the general approach here, because there are a lot of comments on them. For the reasons mentioned in previous responses, I would like to keep the name InputSensor.

2021-08-24 06:46 UTC, aklawonn commented on examples/example_multiple_sensors.py
> +taralli_solver(problem, n_walkers=n_walkers, n_steps=n_steps)
Similar to a comment above: post-processing is happening here within the taralli solver. A result plot is generated when running the script.

2021-08-24 06:59 UTC, aklawonn commented on examples/example_linear_regression.py
> +        return a * x + b
Valid point. I opened an issue on that matter.

2021-08-24 07:03 UTC, aklawonn commented on probeye/forward_model.py
> +            The name of the sensor, e.g. 'Deflection-Sensor bottom-left'.
I think you can see the deflection as an input, it the experiment is deflection-controlled, but I guess it's more clear for another example. I changed it to 'Time'.

2021-08-24 07:10 UTC, aklawonn commented on probeye/forward_model.py
> +        self.error_metric = error_metric
I think if a relative error makes sense, also the experimental datum should not become zero. I like the definitions "model - measured" and "1 - model/measured" because positive/negative numbers mean, that your model error is positive/negative. In the other way of defining it the meaning flips, which is a bit confusing to me.

2021-08-24 07:16 UTC, aklawonn commented on probeye/forward_model.py
> +        input_sensors : list[InputSensor]
I think this distinction between input and parameters is quite common (see for example https://en.wikipedia.org/wiki/Uncertainty_quantification where the input is called 'x' and the parameters 'theta'). This is distinction is necessary, for example when it comes to computing the jacobian.

2021-08-24 07:18 UTC, aklawonn commented on probeye/forward_model.py
> +        exp_inp : dict
See responses above. I would argue there are no deterministic values in real-world data, since all values come from measurements.

2021-08-24 07:20 UTC, aklawonn commented on probeye/forward_model.py
> +        response_dict = {output_sensor.name: self.response(inp, output_sensor)
This is probably solved when issue 3 is solved.

2021-08-24 07:24 UTC, aklawonn commented on probeye/forward_model.py
> +    def error_function(self, exp_inp, prms, output_sensor, ye):
I thought about it, but I forgot why I didn't do it. Certainly worth to look into. I opened an issue on that front.

2021-08-24 07:26 UTC, aklawonn commented on probeye/inference_problem.py
> +        self._prior_classes = {'normal': PriorNormal,
You can add your own prior-class via InferenceProblem.add_prior_class.

2021-08-24 07:30 UTC, aklawonn commented on probeye/inference_problem.py
> +        """Provides n_calibration_prms attribute."""
'calibration'-parameters are the parameters that are supposed to be inferred. 'const'-parameters have a fixed value, and are not inferred.

2021-08-24 07:38 UTC, aklawonn commented on probeye/inference_problem.py
> +            Either 'model' (for a model parameter), 'prior' (for a prior
'model', 'noise' and 'prior' are the parameter types. 'calibration' and 'const' are the parameter roles. each parameter of any type can have the role 'calibration' (when it should be inferred) or 'const' (when it should not be inferred). Prior parameters are always added automatically with the role 'const', when adding a 'calibration'-parameter to the problem. if a prior-parameter should not be 'const', you can change its role to 'calibration' with the method InferenceProblem.change_parameter_role.

2021-08-24 07:42 UTC, aklawonn commented on probeye/inference_problem.py
> +            If the added parameter is a 'calibration'-parameter, this argument
Yes, I chose that name, because the term 'latent variable' is often used when comparing it to 'observable variables'. Here, however, the other group is not 'observable variables' but simply 'constants'. Also, I thought the term 'calibration'-parameter is easier to understand for someone who wants to use probeye, but isn't too familiar with calibration problems.

2021-08-24 07:43 UTC, aklawonn commented on probeye/inference_problem.py
> +            prior_type = prior[0]  # e.g. 'normal', 'lognormal', etc.
Maybe there's a better way to do it as it is now. But you can add your own prior class with InferenceProblem.add_prior_class.

2021-08-24 07:48 UTC, aklawonn commented on probeye/inference_problem.py
> +        self._noise_models[output_sensor_name] = noise_model
Good point, correlations cannot be defined yet. I guess this is something for a future version though.

2021-08-24 07:54 UTC, aklawonn commented on probeye/priors.py
> +    this class is defined is to avoid storing any numeric values for any of the
Well I can't just delete 'is defined' here, because then the sentence doesn't make any sense anymore. Instead, I changed 'defined is' to 'implemented was'.

2021-08-24 07:57 UTC, aklawonn commented on probeye/noise.py
> +    def loglike_contribution(self, model_error_vector, prms):
Aren't we calling the output of the sensor_metric function 'model error' so far?

2021-08-24 08:20 UTC, aklawonn commented on probeye/solver.py
> +def taralli_solver(problem, n_walkers=20, n_steps=1000, plot=True,
I moved it.

2021-08-24 08:25 UTC, aklawonn commented on probeye/priors.py
> +    def generate_samples(self, prms, size, seed=None):
Do you mean the generate_samples method? I think this is a general method which just belongs to the prior-class. I mean, strictly speaking, also the __call__ method (which evaluates the logpdf) is not describing the inference problem, but just a helper function in the inference. Maybe we can have a chat on that matter.

2021-08-24 08:27 UTC, TTitscher requested changes
Thanks for putting that together and also adding tests, nice!

As commented in the `ModelTemplate` code, I just realized that the `__call__` method is called once **per output sensor** instead of really just once. That needs to be changed and I'll approve the PR as soon as this is fixed.

Also the recommendation to overwrite the `reponse` method may be troublesome as this makes separating an expensive calculation from a cheap postprocessing (to just extract the response for a given sensor) not trivial.

Apart from that I added some suggestions here and there for you to consider.

2021-08-24 08:27 UTC, TTitscher commented on probeye/subroutines.py
> +    """
Suggestion: See if
~~~py
def underlined_string(string)
    return tabulate(None, headers=[string], tablefmt="grid")
~~~
looks good enough for you.

2021-08-24 08:27 UTC, TTitscher commented on probeye/inference_problem.py
> +from copy import deepcopy as dc
I was a bit confused when i saw `dc` in the code and would find `copy.deepcopy` more explicit.

2021-08-24 08:27 UTC, TTitscher commented on probeye/inference_problem.py
> +    def info(self, print_it=True, include_experiments=False):
I recommend the `tabulate` package to print this kind of info. With the option `tablefmt="latex"`, you could directly put that into a paper or presentation. Also, it would get rid of the string formatting functions in `subroutines`.

2021-08-24 08:27 UTC, TTitscher commented on probeye/parameter.py
> +        self.tex = prm_dict['tex']
```suggestion
        self.__dict__ = prm_dict
```
would do the same.

2021-08-24 08:27 UTC, TTitscher commented on probeye/inference_problem.py
> +            prms_info_str += tcs(prm_name, f"{parameter.info}", col_width=w)
I would think about if anything related to the parameters should go into a `Parameters.info(...)` to be called separately. (Also having a LaTeX parameter-table for a model overview in mind...)

2021-08-24 08:55 UTC, aklawonn commented on probeye/inference_problem.py
> +    def logprior(self, theta):
This is probably a good idea, however, right now, I don't really see a place where else to put them. I will have to think about this a bit. I would suggest, for the first version, we leave it as is. Otherwise, the structure might change considerably to what was presented in the meeting where we first presented probeye.

2021-08-24 08:56 UTC, aklawonn commented on probeye/inference_problem.py
> +    def sample_from_prior(self, prm_name, size):
See response above.

2021-08-24 09:12 UTC, aklawonn commented on probeye/parameter.py
> +        self.tex = prm_dict['tex']
You're right, that's much shorter. But then you could essentially add any dictionary to ParameterProperties without any checks if all required keys are there. Of course, you could add some checks then, but I thought, the way it is implemented right now, would just throw an error if a required key does not appear. Also, I thought it is easier to see at one glance which attributes this class has in the way it is implemented now compared to the short version.

2021-08-24 09:17 UTC, aklawonn commented on probeye/inference_problem.py
> +from copy import deepcopy as dc
No problem, I changed it.

2021-08-24 09:48 UTC, aklawonn commented on examples/example_two_models.py
> +y_quadratic_true = alpha_true * x_test**2 + b_true
Good point, done.

2021-08-24 09:55 UTC, aklawonn commented on probeye/priors.py
> +        return getattr(stats.norm, method)(x, loc, scale)
Your first point is a good idea, I changed that. Regarding the meta-programming, I wanted to avoid it since it is rather slow.

2021-08-24 15:01 UTC, joergfunger commented on examples/example_linear_regression.py
> +taralli_solver(problem, n_walkers=n_walkers, n_steps=n_steps)
Yes, I did. But I guess it would be best to move this a separate postprocessing call instead of hiding that in the wrapper class for Taralli. Maybe something to be done in a subsequent step and not in this first version, in that case could you add an issue?

2021-08-24 15:04 UTC, joergfunger commented on probeye/priors.py
> +    def generate_samples(self, prms, size, seed=None):
yes, and that is why I think it is not part of the description of the inference problem, but already part of the solution, which should be moved to the inference engine

2021-08-24 15:11 UTC, joergfunger commented on examples/example_multiple_sensors.py
> +                           fwd_model_name='LinearModel')
Getting rid of the sensor object makes it difficult to store information e.g. at what position the sensor is located. For me, the sensor is just a construct to define what is computed in a postprocessing step of the forward model (so that you can essentially decide what data to be used without changing the forward model). An input sensor is for me less intuitive.

2021-08-24 15:15 UTC, joergfunger commented on probeye/priors.py
> +        return getattr(stats.norm, method)(x, loc, scale)
IMO, this evaluation part should be moved into the inference engine and then everyone can decide how to implement the evaluation of the pdfs (using scipy, pyro, ..)

2021-08-24 15:30 UTC, joergfunger commented on examples/example_multiple_sensors.py
> +class PositionSensor(OutputSensor):
For me, the (output)-sensor in the forward model defines what is to be returned. The input is not necessarily something that is related to an experiment, but could be e.g. the mesh_size used. For me, there is no clear distinction between what is an input and what is a parameter, maybe apart from the fact that the first ones are static (so you could create a response surface with only the parameters being variable), or you could e.g. create the FEM mesh with these parameters (e.g. the mesh) and then only solve for this constant mesh. As such, I feel the forward modul should get variable/latent and static parameters (the latter could even be provided in the constructor or some init function before the actual computation is performed e.g. to create the mesh, factorize the stiffness matrix, compile the fenics form, ..) and then only have inputs (latent) and sensors (outputs).

2021-08-24 15:35 UTC, joergfunger commented on probeye/forward_model.py
> +            The name of the sensor, e.g. 'Deflection-Sensor bottom-left'.
valid point, in a displacement-controled setting the displacement is an input. Even though I think that should not be called sensor, but i suggest that we have (as you already discussed in the previous responses) an online meeting on that on what we think is a sensor/input/output/data,..

2021-08-24 15:37 UTC, joergfunger commented on probeye/forward_model.py
> +        self.error_metric = error_metric
as for the relative definition of the error there is certainly not a right or wrong. Related to the error_metric, we should probably discuss where this should be implemented (e.g. at the noise model, the sensor) and how (as a function, as a string).

2021-08-24 15:39 UTC, joergfunger commented on probeye/forward_model.py
> +        input_sensors : list[InputSensor]
see my comments above, thus the x parameters can be provided a priori and do not have to be part of the call function, because they are always constant (and allow you to appropriately set up the model).

2021-08-24 15:44 UTC, joergfunger commented on probeye/forward_model.py
> +        exp_inp : dict
From the modeler perspective, it does not make a difference whether the input is from the experiment, or if it is prescribed by the one doing the inference. What matters IMO is whether input data is constant/deterministic or variable/latent. I realize that exp. input might be determinstic, but still can't be stored in an init function if the same forward model is used for multiple datasets (with potentially different deterministic values). But maybe it makes sense to exclude that option so that people would have to create multiple forward models with different deterministic inputs.

2021-08-24 15:53 UTC, joergfunger commented on probeye/inference_problem.py
> +        self._prior_classes = {'normal': PriorNormal,
so why do we need to store these prior_classes in the inference problem, I would argue we just need the priors and then instantiate an object of each prior type (e.g. PriorNormal?)

2021-08-24 15:55 UTC, joergfunger commented on probeye/inference_problem.py
> +        """Provides n_calibration_prms attribute."""
maybe we should develop a clear wording, because we sometimes talk about latent, variable or calibration parameters often refering to the same concept (or sometimes maybe not:)

2021-08-24 15:59 UTC, joergfunger commented on probeye/inference_problem.py
> +            If the added parameter is a 'calibration'-parameter, this argument
"In statistics, latent variables (from Latin: present participle of lateo (“lie hidden”), as opposed to observable variables) are variables that are not directly observed but are rather inferred" from [wikipedia](https://en.wikipedia.org/wiki/Latent_variable). I would interpret that as the calibration parameters (because we can't observe them). But maybe that is a point for the next meeting as well.

2021-08-24 16:03 UTC, joergfunger commented on probeye/inference_problem.py
> +    def change_parameter_role(self, prm_name, const=None, prior=None,
Why wouldn't you just change the defition of the parameters, instead of first defining them as variable and then afterwards redefining them as const? As for the prior-prior option, you can define the hyperparameter with its prior first (then it is automatically defined as being latent, and only afterwards define the prior of a model parameter with this hyperparameter.

2021-08-24 16:12 UTC, joergfunger commented on probeye/noise.py
> +    def loglike_contribution(self, model_error_vector, prms):
Here it also seems to be necessary to define the wording. For me, the model error is the difference between exp data and forward model (without applying some metric to make it relative/abs or any other transformation). But we just have to agree on the wording.

2021-08-25 07:02 UTC, TTitscher commented on examples/example_multiple_sensors.py
> +                           fwd_model_name='LinearModel')
As I said, I understand the concept of a sensor as a nice way to connect the model and the data. But I see little/no benefit from using/subclassing these `Input/OutputSensor` classes, when I could also use a string, a number, a custom `Sensor` class, a dictionary with inputs, ... 

But maybe having these classes makes it easier for users to follow the sensor *concept*.

2021-08-25 07:55 UTC, aklawonn commented on probeye/subroutines.py
> +    """
I looked at what you started with tabulate before, and revised the InferenceProblem's info method accordingly.

2021-08-25 07:57 UTC, aklawonn commented on probeye/inference_problem.py
> +    def info(self, print_it=True, include_experiments=False):
Done, now the info-printout (more specifically, the tables appearing in it) is constructed with tabulate.

2021-08-25 07:58 UTC, aklawonn commented on probeye/inference_problem.py
> +            prms_info_str += tcs(prm_name, f"{parameter.info}", col_width=w)
I implemented that. Now, the Parameter's class has some info-methods using tabulate.

2021-08-25 08:38 UTC, aklawonn commented on examples/example_linear_regression.py
> +taralli_solver(problem, n_walkers=n_walkers, n_steps=n_steps)
All right, I opened an issue on that matter.

2021-08-25 08:50 UTC, aklawonn commented on probeye/forward_model.py
> +        input_sensors : list[InputSensor]
The x-values cannot be provided a priori, because they differ from experiment to experiment. They are the 'observable variables' while theta contains the 'latent variables'.

2021-08-25 08:52 UTC, aklawonn commented on probeye/forward_model.py
> +        self.error_metric = error_metric
Right, I think this comment is covered by the issue on the error-metric.

2021-08-25 09:09 UTC, aklawonn commented on probeye/inference_problem.py
> +        self._prior_classes = {'normal': PriorNormal,
Solid point, I opened an issue on that matter.

2021-08-25 11:56 UTC, aklawonn commented on probeye/forward_model.py
> +        overwritten by the user's response method.
You're right, I looked into it, and revised the __call__ method of ModelTemplate accordingly.

2021-08-25 11:58 UTC, aklawonn commented on probeye/forward_model.py
> +        ym = self(exp_inp, prms)[output_sensor.name]
Yep, that implementation wasn't a bright star in the efficiency-sky. I worked that over.

2021-08-25 12:31 UTC, TTitscher approved these changes

2021-08-25 13:21 UTC, aklawonn commented on examples/example_multiple_sensors.py
> +class PositionSensor(OutputSensor):
I see what you understand under a sensor in this context. However, I think that this understanding is not very intuitive. For you, a sensor is essentially an outward directed data-channel from some computed result by a forward model. But when I think of a sensor, I think of a physical device that measures something. That's why I find it very intuitive to associate a sensor class with the data from an experiment - because all this data was measured by physical sensors. The forward model now takes some of these sensor-measurements as input. Hence, for the forward model sees these sensors are input sensors. And the values of the input sensors are not static, since they vary from experiment to experiment. The inputs you are mentioning (e.g. the mesh-size) are just constants, i.e. constant parameters of the forward models. These can either be defined within the forward model without introducing them in the inference problem, or they can just be defined as constants in the inference problem. The forward model in the current implementation has also output sensors how you understand them. But in my understanding they are just abstract concepts that mirror the actual sensors from the experimental setup.

2021-08-25 15:54 UTC, joergfunger commented on probeye/forward_model.py
> +        input_sensors : list[InputSensor]
I would say the observable variables are usually the outputs, but I realize that there are deterministic parameters that are constant for each model (for all experiments) and others that are constant but depend on the experiment. So we do not distinguish between those two, so inputs are the deterministic parameters, whereas prms are the ones we are calibrating.

2021-08-28 13:04 UTC, aklawonn commented on examples/example_linear_regression.py
> +taralli_solver(problem, n_walkers=n_walkers, n_steps=n_steps)
I separated the taralli solver routine from the postprocessing. Also, there is no taralli.py or taralli subpackage anymore, so there shouldn't be any import-clashes anymore.

2021-08-29 08:27 UTC, aklawonn commented on examples/example_linear_regression.py
> +        return a * x + b
By now, this problem, which was also mentioned by @TTitscher has been resolved. The corresponding issue #3 was closed.

2021-08-29 08:30 UTC, aklawonn commented on probeye/forward_model.py
> +        response_dict = {output_sensor.name: self.response(inp, output_sensor)
Issue #3 was closed, so this point here should be covered by now.

2021-08-29 08:31 UTC, aklawonn commented on probeye/inference_problem.py
> +        self._prior_classes = {'normal': PriorNormal,
Issue #6, which was dealing with this point was closed. The prior classes have been decoupled from the InferenceProblem.

2021-08-29 08:35 UTC, aklawonn commented on probeye/inference_problem.py
> +    def logprior(self, theta):
I restructured the package into a definition and an inference subpackage. In the definition package, there are no computing routines anymore. All computing routines are moved to the inference subpackage.

2021-08-29 08:37 UTC, aklawonn commented on probeye/priors.py
> +    def generate_samples(self, prms, size, seed=None):
The separation into a definition and an inference subpackage, where all computing routines have been moved to the inference subpackage resolved this point.

2021-08-29 08:40 UTC, aklawonn commented on probeye/priors.py
> +        return getattr(stats.norm, method)(x, loc, scale)
The prior's computing routines have been moved to the inference subpackage and are not part of the problem definition anymore.

2021-08-29 10:09 UTC, aklawonn commented on probeye/inference_problem.py
> +    def change_parameter_role(self, prm_name, const=None, prior=None,
One can now directly define prior-parameters as being calibration parameters without utilizing change_parameter_role (see test_prior_calibration.py for an example). However, the method change_parameter_role is still usefull to switch parameters from const to calibration (latent) or vice versa.

2021-08-31 13:43 UTC, atulag0711 commented on probeye/definition/forward_model.py
> +        return jac
Hi, Alex,
Thanks for the well structured and commented code. Its super sleek and I think very comprehensive. 
About the Jacobian above, wouldn't that be beneficial to have an option to check if the forward solver passes adjoint/adoint operator. If so then that should be returned by the Jacobian operator. If the solver is not differentiable then only CD based Jacobian needs to be passed. Just an idea.

2021-08-31 13:46 UTC, atulag0711 commented on probeye/definition/forward_model.py
> +        return jac
Apart from this I think our video call clarified a lot of stuff. waiting for 1.0 then Ill build a pyTorch wrapper around this.

2021-08-31 13:49 UTC, joergfunger commented on probeye/definition/forward_model.py
> +        return jac
We have to distinguish between a jacobian (the derivative of all model outputs with respect to all parameters = matrix) and a jacobian of the loglikelihood with respect to the parameters (just a vector).

2021-08-31 14:04 UTC, atulag0711 commented on probeye/inference/taralli_/postprocessing.py
> +        emcee_model.summary()
IMHO, there can be solver specifi viz but there should be a common viz for all taralli/Torch/tensorflow ..right. Ultimately whatever we use we have posterior samples in array or form of  approximate distribution. (VI)

2021-08-31 14:05 UTC, atulag0711 commented on probeye/inference/taralli_/priors.py
> +    return prior_object
Like priors, noise model will also be solver specific. For eg torch will need torch distributions

2021-08-31 14:36 UTC, atulag0711 commented on probeye/definition/forward_model.py
> +        return jac
@joergfunger Hi Jorg. Yes valid point. I think if dL/d\theta  = dL/dy * dy/d\theta.  dy/d\theta is a matrix and it comes from the forward solve which needs to be stored somewhere (also updated after every solve). dL/dy is computed by autodiff (e.g torch).  These two gives us dL/d\theta which is needed to move to next step in the optimizer. Please correct me if I am wrong/unclear.

Implementation wise, the Jacobian of the solver (dy/d\theta) can be an operator (FEnics) and if supplied by the likelihood function should be able to give adjoints.

2021-08-31 14:51 UTC, joergfunger commented on probeye/definition/forward_model.py
> +        return jac
The difference is that we can always compute dL/dtheta if we have dy/dtheta, but that might come at a significant cost. The derivative of dL/dtheta can be solved by an adjoint problem, and in this case we do not need the complete full matrix. That is particularly relevant for problems with many parameters. However, I think we should move this discussion to a separate issue and consider the current implementation as a starting point for probeye 0.1 (or 1.0 - whatever we think isapprorpiate).

2021-09-03 07:11 UTC, aklawonn commented on probeye/inference_problem.py
> +        if sensor_values is None:
I wanted to make the user use keyword arguments. But I guess the arguments are very different here (no risk of confusing them) so I converted them into positional arguments. Also I saw (which I did not know before), that you can still provide positional arguments in form of keyword arguments when calling the function, so that's nice.

2021-09-03 09:57 UTC, aklawonn commented on tests/integration_tests/test_prior_calibration.py
> +        out_1 = Sensor("y")
I changed the code in the forward model's call-function, so that also the y-sensor is used.

2021-09-03 09:57 UTC, aklawonn commented on tests/integration_tests/test_two_models.py
> +                return {'y': a * x + b}
see above

2021-09-03 10:19 UTC, aklawonn commented on tests/integration_tests/test_linear_regression.py
> +        out_1 = Sensor("y")
I see it as Thomas does.  You have both options to define the input. Via an input sensor, as it is currently demonstrated in the linear_regression example, or via Sensor-attributes, as demonstrated in the multiple_sensors example. In fact, you don't have to provided any input sensors at all when defining the forward model (i.e. currently, you have pass an empty list for the input sensors).

2021-09-03 10:30 UTC, aklawonn commented on examples/example_multiple_sensors.py
> +                           fwd_model_name='LinearModel')
A sensor has two tasks. First, it connects the model response to the corresponding experimental data by virtue of his name attribute (i.e. the model produces an 'y' value, so there needs to be an 'y' value in the experimental data) which is required for the noise model to work. Second, it allows to define sensor-constants like its position. The latter, however, is essentially also experimental data (e.g. someone measured the sensor position) which should only be stored at one location, which currently is the sensor-object. This sensor-object is currently attached to the forward model, when the latter is instantiated. I would not pass additional instances of the same sensor object (including the constants) to another module because then you have the same data at multiple locations. If these modules need the sensor-constants (e.g. maybe the noise model needs them for some position-correlation), they can just get it from the forward model by referring to the sensor's name. Bottom line is, I would not pass sensor-objects to every module instead of just the sensor's name. Also I would not everywhere pass just the sensor name, because then you can't define sensor-constants.

2021-09-03 10:34 UTC, aklawonn commented on probeye/definition/forward_model.py
> +        return jac
Hey Atul, thanks for your feedback! Currently, I have removed the computation of the jacobian from the code, as it was more of a default for which there will be faster versions in the different inference engines. So if you use Torch, you can just use their methods for computing derivatives without having to consider some existing methods in probeye for that.

2021-09-03 10:37 UTC, aklawonn commented on probeye/inference/taralli_/postprocessing.py
> +        emcee_model.summary()
Good points! Yes, the post-processing will need some further work in the future. Currently, there is just a simple skeleton so that you get some output after calling the taralli routines.

2021-09-03 10:39 UTC, aklawonn commented on probeye/inference/taralli_/priors.py
> +    return prior_object
Yes indeed, you can define your own priors for Torch. Just check out probeye/inference/taralli_/priors.py to see the priors that are currently used for the taralli setup. In a similar structure, you would write your Torch priors to probeye/inference/pytorch_/priors.py (not existing yet).

2021-09-06 09:59 UTC, joergfunger reviewed
There are only a couple of small remarks left. The only remaining thing is the separation between pms and input sensors, which I don't think is intuitive.

2021-09-06 09:59 UTC, joergfunger commented on probeye/definition/noise_model.py
> +        experiment_names_ : str, list[str]
not sure what the difference is here, one is the name, the other the actual data structure? Why do I need both?

2021-09-06 09:59 UTC, joergfunger commented on probeye/definition/forward_model.py
> +    def __init__(self, prms_def_, input_sensors, output_sensors):
I'm still struggling with the difference between prms and input_sensors, are the first ones the variable ones to be calibrated and the second one are the measured deterministic data? And why is that important for someone writing the forwardmodel template?

2021-09-06 09:59 UTC, joergfunger commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
Is that the Baseclass, or a template that others should copy from? Isn't this class rather a special uncorrelated Gaussian noise class instead of a template?

2021-09-06 09:59 UTC, joergfunger commented on probeye/definition/sensor.py
> +class PositionSensor(Sensor):
I would provide the coordinates in a single array (makes using that easier, because you can directly access all coordinates by extracing a single row. The dimension would IMO also be flexible.

2021-09-06 11:10 UTC, aklawonn commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
This is a template-class, other noise models should be derived from. An example is the noise class in probeye/inference/taralli_/noise_models.py. I don't see why it would be a special case of an uncorrelated normal noise, since it does not compute anything.

2021-09-06 11:15 UTC, aklawonn commented on probeye/definition/noise_model.py
> +        experiment_names_ : str, list[str]
The first argument states a list of experiment-names that are in the scope of the noise model. The second argument is essentially the experiment database of the problem (the dict with all the experimental data). This second argument is only used to check if the experiment names given in the first argument appear in the problem's experimental database, and if those experiments are consistent with the noise model (i.e. if they have all sensors that the noise model requires). Long story short: the second argument is just for checking the first argument.

2021-09-06 11:25 UTC, joergfunger commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
What about the error, isn't that already some computation?

2021-09-06 11:26 UTC, aklawonn commented on probeye/definition/sensor.py
> +class PositionSensor(Sensor):
I added an attribute with all coordinates as a vector. However, I would leave the dimension at three for this simple PositionSensor. A sensor class with more than three coordinates sounds like a custom position sensor class to me.

2021-09-06 11:27 UTC, aklawonn commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
No, since it requires the error_function which is undefined in this class.

2021-09-06 11:37 UTC, joergfunger commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
I think the question is, if all noise models need an error function that is called by some tool - if this is not the case then this would not necessarily be a method of the base class?

2021-09-06 11:46 UTC, aklawonn commented on probeye/definition/forward_model.py
> +    def __init__(self, prms_def_, input_sensors, output_sensors):
Input sensors contain measured data that - in general - differs from experiment to experiment, and which is required by the forward model as an input argument. Those values are always fixed, deterministic and will not be inferred, which distinguishes them from the prms-argument, which are the parameters that should be inferred.

2021-09-06 11:52 UTC, aklawonn commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
I would think that this setup is useful for the majority of the problems. However, this does not mean that it will always apply. There are probably cases where you need something different. But then, you would just overwrite the error method with your custom error-method. I think for most users it will be helpful to see how this default method looks like compared to the case where we would provide no guidance at all.

2021-09-06 11:56 UTC, joergfunger commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
For me, the noise model is not yet a pure problem description, or vice versa not sufficient to describe all possible noise models (independent of the implementation), e.g. Gaussian normal noise is a standard that should be part of the problem definition library (not the inference engine).

2021-09-06 13:52 UTC, aklawonn commented on probeye/definition/noise_model.py
> +        experiment_names_ : str, list[str]
The second argument is now an attribute of the noise model, and hence not required as an input anymore.

2021-09-07 07:22 UTC, joergfunger commented on probeye/definition/sensor.py
> +class PositionSensor(Sensor):
what about dimensions 1 and 2?

2021-09-07 10:24 UTC, aklawonn commented on probeye/definition/sensor.py
> +class PositionSensor(Sensor):
I updated the PositionSensor for the 1D and 2D case. It's already pushed.

2021-09-07 10:25 UTC, aklawonn commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
As discussed, I moved the NormalNoise to the definition part of the package.

2021-09-07 12:37 UTC, aklawonn commented on probeye/definition/noise_model.py
> +class NoiseModelTemplate:
Also, all Template classes were renamed to Base classes.

2021-09-07 12:38 UTC, aklawonn commented on probeye/inference/taralli_/postprocessing.py
> +        emcee_model.summary()
This discussion is continued in issue #8.

2021-09-07 12:42 UTC, aklawonn commented on probeye/definition/forward_model.py
> +    def __init__(self, prms_def_, input_sensors, output_sensors):
As discussed on the phone, the name input sensors will be kept for now.

2021-09-07 12:44 UTC, aklawonn commented on examples/example_linear_regression.py
> +problem.add_experiment(f'TestSeries_1', sensors={'x': x_test, 'y': y_test},
As discussed on the phone, the sensor terminology will be kept for now.

2021-09-07 13:52 UTC, aklawonn commented on examples/example_multiple_sensors.py
> +class PositionSensor(OutputSensor):
As discussed on the phone, the sensor terminology will be kept for now.

2021-09-07 13:53 UTC, aklawonn commented on examples/example_multiple_sensors.py
> +inp_1 = InputSensor("time")
As discussed on the phone, the sensor terminology will be kept for now.

2021-09-07 13:53 UTC, aklawonn commented on probeye/forward_model.py
> +            The name of the sensor, e.g. 'Deflection-Sensor bottom-left'.
As discussed on the phone, the sensor terminology will be kept for now.

2021-09-07 13:53 UTC, aklawonn commented on probeye/forward_model.py
> +        exp_inp : dict
As discussed on the phone, the sensor terminology will be kept for now.

2021-09-07 13:54 UTC, aklawonn commented on probeye/forward_model.py
> +    def error_function(self, exp_inp, prms, output_sensor, ye):
The error functions - as discussed - have been moved to the noise model.

2021-09-07 13:55 UTC, aklawonn commented on tests/integration_tests/test_linear_regression.py
> +        out_1 = Sensor("y")
As discussed on the phone, the sensor terminology will be kept for now.

2021-09-07 13:57 UTC, aklawonn commented on probeye/inference_problem.py
> +        self._noise_models[output_sensor_name] = noise_model
I opened an issue for the correlation methods (see issue #9).

2021-09-08 08:11 UTC, aklawonn commented on probeye/inference_problem.py
> +        """Provides n_calibration_prms attribute."""
As discussed, calibration-parameters are now called latent parameters.

2021-09-08 08:11 UTC, aklawonn commented on probeye/inference_problem.py
> +            If the added parameter is a 'calibration'-parameter, this argument
As discussed, calibration-parameters are now called latent parameters.

2021-09-08 08:13 UTC, aklawonn commented on probeye/noise.py
> +    def loglike_contribution(self, model_error_vector, prms):
By now, one can simply choose between an additive or a multiplicative error function.

2021-09-08 09:43 UTC, TTitscher commented on probeye/definition/inference_problem.py
> +        return self._parameters
What is the advantage of this decorator over just storing `self.parameters`?

2021-09-08 10:33 UTC, aklawonn commented on probeye/definition/inference_problem.py
> +        return self._parameters
These private attributes should not be directly edited from outside, but they should be accessible. So, by the current setup you can access the parameters attribute via problem.parameters, but you cannot edit it e.g. via problem.parameters['a'] = {...}.

2021-09-08 10:47 UTC, TTitscher commented on probeye/definition/inference_problem.py
> +        return self._parameters
I agree with the behavior you describe, but the code does not complain when I do
`problem.parameters["a"].type = 5`
or 
`problem.parameters["new_prm"] = ParameterProperties({...})`

2021-09-08 13:39 UTC, aklawonn commented on probeye/definition/inference_problem.py
> +        return self._parameters
Good point, I opened an issue on that matter (issue #10). However, I did not do anything about it yet as this does not affect the normal use of probeye.

2021-09-10 09:47 UTC, joergfunger approved these changes

2021-09-10 10:10 UTC, merged