Embedded bias initial implementation
BAMresearch/probeye pull request #114
Opened 2024-08-26 14:31 UTC by danielandresarcones

This is the initial implementation of embedded bias approaches to be integrated in probeye. It provides a working implementation for the computation of inverse problems with embedded bias.
- Currently the bias embedding must be implemented manually in the forward model. Ideally, this should not be the case and the bias should be specified in the parameters and variables description.
- The additions take care of the MCMC solver with stochastic forward model response and introduce four embedded likelihood formulations: ABC Moment matching, Global Moment Matching, Relative Global Moment Matching and Independent Normal. The details on the implementations will eventually be published.
- Kennedy and O'Hagan-type formulations are not implemented in this PR and have been eliminated from the branched code.
- Tests and one simple example for the documentation have been added.

2024-08-28 10:46 UTC, danielandresarcones commented
This update also implements the proposed solution of Issue #90 .

2024-08-28 11:14 UTC, danielandresarcones commented
Tests cover is not 100% on the new implementations as there probably will be changes in the definition of the bias in the near future. The lack of cover is precisely on that front, the checks that some parameter definitions are correctly imported to the models. Nevertheless, they can be tested if considered necessary.

2024-10-22 11:57 UTC, aradermacher commented on docs/examples/bias.py
> +        expansion = chaospy.generate_expansion(self.pce_order, bias_dist)
It should be b_dist instead of bias_dist

2024-10-22 11:59 UTC, aradermacher reviewed
Thanks Daniel, 
I had problems running the example file, because of a typo (see comment)
Furthermore, during creating a new env I run into an error with python 3.13. Changing to 3.10 solved it.

2024-10-23 06:30 UTC, danielandresarcones commented on docs/examples/bias.py
> +        expansion = chaospy.generate_expansion(self.pce_order, bias_dist)
I missed that totally, thanks!

2024-10-23 06:33 UTC, danielandresarcones commented
Do you remember what whas the error with python 3.13? I think probeye had some problems with it at some point, not necessarily the embedded bias implementation only.

2024-10-23 06:47 UTC, aradermacher commented
> Do you remember what whas the error with python 3.13? I think probeye had some problems with it at some point, not necessarily the embedded bias implementation only.

Yes it was something with the required packages (but I didn't saved the message sorry). So I think it's a general problem of probeye and not with your implementation.

2025-03-03 13:57 UTC, danielandresarcones commented
This version is the first step towards #115. Main changes:

- Parallelization of walkers in emcee-based solvers.
- Simplified creation of new likelihoods (bias likelihoods were created in the new way). They can be defined without having to deal with the correlation features
- Fixed the bias implementations
- Solved copy/deepcopy issue from #90

2025-05-19 13:32 UTC, joergfunger requested changes
nice work, thanks. There are a couple of remarks or thinks that I have difficulties to relate to the current paper. It would be nice if the naming conventions in the paper and the source code are somehow overlapping, such that the paper serves as a scientific documentation to the source code.

2025-05-19 13:32 UTC, joergfunger commented on docs/examples/bias.py
> +class LinearModel(ForwardModelBase):
This is an elegant way of using the flexibility with the Forward model output to return directly a distribution rather then sensor output. But that means the ForwardModel is not compatible with other deterministic ForwardModels. Would it make sense to Create a wrapper for the StochasticForwardModels, that takes as input a deterministic forward model (as well as the definition of the embedding and the parameters of the PCE) and then wraps that pce expansion as a blackbox, anyone else could then easily add his/her model, and then you could also check, whether the Forward model send to the embedded solver is actually a stochastic forward model.

2025-05-19 13:32 UTC, joergfunger commented on docs/examples/bias.py
> +        m = inp["a"]
the naming is not clear, (I guess m stands for mean, b for bias), but some short documentation would be nice

2025-05-19 13:32 UTC, joergfunger commented on docs/examples/plot_correlation_1D.py
> +# scipy_solver = MaxLikelihoodSolver(problem, show_progress=False)
why is that uncommented?

2025-05-19 13:32 UTC, joergfunger commented on docs/examples/plot_correlation_1D.py
> +problem.forward_models.pop("LinearModel")
Why is the model first removed and then added?

2025-05-19 13:32 UTC, joergfunger commented on probeye/definition/inverse_problem.py
> +        # the internal forward models list enables reusing the same problem in different
not sure I understand that, why do we need internal forward models? Why don't you define difference inference problems when using different solvers?

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +        std_model, std_meas, stds_are_scalar = self.std_values(prms)
not sure I understand what that methods does? Could you add some docs?

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +        variance_residual = np.var(residual_vector)
I think this is assuming the mean to be known, but since it is estimated, you have to divide by n-1 rather than n, use ddof=1 in this case

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +        population_variance = (
I think the variable notation is not matching with the paper, it would be nice if that could be improved (e.g. population variance is defined differently in the paper in eq. 31)

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +        sigma_model_population = np.sqrt(
not sure I see this in eq. 42

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +        sample_variance = np.var(np.divide(response_vector[0], sigma_model_sample)) + 1
not sure I would I see the similarity to eq. 47 in the paper

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +    This class implements the relative global moment matching likelihood model.
not sure what the difference between the scaled global moment matching and the unscaled version is? Is there a reference in the paper for that likelihood?

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +        sigma_model_population = np.sqrt(
is that eq. 42?

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +        )
not sure I can follow here with the equations from the paper

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/bias/likelihood_models.py
> +                + np.log(2 * np.pi * np.square(sigma_model_sample))
where is the -ny/2 from eq. 28? and where is the inverse in the last term?

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/scipy/solver.py
> +            self.problem.internal_forward_models[fwd_name] = forward_model
see above not sure what these internal forward models are

2025-05-19 13:32 UTC, joergfunger commented on probeye/inference/solver.py
> +        self.problem = cp.copy(problem)
why is a copy here sufficient?

2025-05-26 10:34 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +        )
Updated

2025-05-26 10:35 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +                + np.log(2 * np.pi * np.square(sigma_model_sample))
See updated version

2025-05-26 10:35 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +        sigma_model_population = np.sqrt(
See updated version

2025-05-26 10:35 UTC, danielandresarcones commented on docs/examples/plot_correlation_1D.py
> +problem.forward_models.pop("LinearModel")
Forgotten from debugging, removed

2025-05-26 10:36 UTC, danielandresarcones commented on docs/examples/plot_correlation_1D.py
> +# scipy_solver = MaxLikelihoodSolver(problem, show_progress=False)
Forgotten from debugging, removed

2025-05-26 10:36 UTC, danielandresarcones commented on docs/examples/bias.py
> +        m = inp["a"]
Modified all the examples for consistent naming. Now "a" is the slope and "b" is the cross with the y-axis.

2025-05-26 10:37 UTC, danielandresarcones commented on docs/examples/bias.py
> +class LinearModel(ForwardModelBase):
Agree, it will be the case for the reimplementation of probeye. For now it remains as something the user must consider when building their forward models.

2025-05-26 10:45 UTC, danielandresarcones commented on probeye/inference/scipy/solver.py
> +            self.problem.internal_forward_models[fwd_name] = forward_model
These are here to solve the copy/deepcopy problem. See #90 for full detail, but the problem is triggered when several solvers access the problem sequentially. FEniCS(X) models cannot be deepcopied, so we need to change them all to copies. Then, the forward model definition is overwritten in the solver initialization, which means that the next solvers will  see only the hull and throw an error. By assigning the translated forward model to the list "internal_forward_models" instead of overwriting "forward_models" and adapting the solvers accordingly, we still preserve the forward model definition after the first call, and is the "internal" one that is overwritten. The deepcopies are therefore not needed as the forward_model definition is still available after running the problem and a new "internal" forward model is created and evaluated from it.

2025-05-26 10:45 UTC, danielandresarcones commented on probeye/inference/solver.py
> +        self.problem = cp.copy(problem)
See above.

2025-05-27 04:39 UTC, joergfunger commented on probeye/inference/scipy/solver.py
> +            self.problem.internal_forward_models[fwd_name] = forward_model
I see, thanks. Just one add-on question. Is it required to store the these internal forward models on the level of the problem definition, or might it be sufficient to store them only locally in the solver, where these copies are actually required?

2025-05-27 06:20 UTC, danielandresarcones commented on probeye/definition/inverse_problem.py
> +        # the internal forward models list enables reusing the same problem in different
See below. It is so you can use a shallow copy to re-use the forward model and not needing to do the pop+readding trick or defining a totally new problem. Just for consecutive uses of the same forward model (relevant for reinitiating a run)

2025-05-27 06:20 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +        variance_residual = np.var(residual_vector)
Updated in the new version

2025-05-27 06:20 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +        sigma_model_population = np.sqrt(
Updated in the new version

2025-05-27 06:21 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +        sample_variance = np.var(np.divide(response_vector[0], sigma_model_sample)) + 1
Updated in the new version

2025-05-27 06:21 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +    This class implements the relative global moment matching likelihood model.
I removed all the likelihoods that are not being used in the paper, they were just variations that I tried at some point.

2025-05-27 06:22 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +        population_variance = (
Updated in the new version

2025-05-27 06:24 UTC, danielandresarcones commented on probeye/inference/bias/likelihood_models.py
> +        std_model, std_meas, stds_are_scalar = self.std_values(prms)
Do you mean extending the docstring of the method or writing a comment there in the application? It is a method from the base class, it is defined in ScipyLikelihoods

2025-05-27 06:29 UTC, danielandresarcones commented on probeye/inference/scipy/solver.py
> +            self.problem.internal_forward_models[fwd_name] = forward_model
We could store them in the solver, but that means modifying the way the likelihood access to them as well (right now it reads from the problem). We could avoid the copy by creating new objects as long as we do not create a hull anymore, which means that definition and execution of the forward model would not be decoupled anymore. If that is still necessary is something we would have to discuss.

2025-05-27 08:50 UTC, joergfunger commented on probeye/inference/scipy/solver.py
> +            self.problem.internal_forward_models[fwd_name] = forward_model
I guess this is something for the redesign of the interface, lt's tackle that in the subsequent redesign.

2025-06-03 07:58 UTC, joergfunger approved these changes
Thanks

2025-06-03 11:45 UTC, merged