export to rdf
BAMresearch/probeye pull request #54
Opened 2021-11-24 14:31 UTC by aklawonn

In this branch, probeye's export-to-rdf feature should be developed. This feature should allow to export a well-defined inference problem to an rdf-file containing data triples relating to an ontology for parameter estimation problems (see probeye/parameter_estimation_ontology.owl), that describe the problem unambiguously.

2022-03-15 09:29 UTC, aklawonn commented
Most of the rdf export work is done at this point. This refers to the export of the problem definition. The inference data is not yet part of the export-framework. However, the export methods (and frankly also some other methods) are is not well tested yet. So I'm gonna work on the testing framework now.

2022-03-23 16:41 UTC, joergfunger requested changes
I will separately look into the owl first, but there are general questions related to the implementation (that is why I did not review everything yet). In addition, the RDF export seems to be mixed up with other changes.

2022-03-23 16:41 UTC, joergfunger commented on CHANGELOG.md
> +- Added an 'interface' submodule which contains a method 'export_to_rdf' that allows to print a defined problem to an rdf-file.
print -> export

2022-03-23 16:41 UTC, joergfunger commented on docs/examples/plot_correlation_1D.py
> +    domain="(0, +oo)",
looks like w weird composition of +oo. Even though I understand this, wouldn't it be better to pass a (lambda) function that evaluates to true (in the domain) or false outside. Thus, it would be much more flexible than pure intervals.

2022-03-23 16:41 UTC, joergfunger commented on probeye/_setup_cfg.py
> +    # just for testing during CI
what is that cfg file about? Not exactly sure that the test option does.

2022-03-23 16:41 UTC, joergfunger commented on probeye/definition/inference_problem.py
> +import urllib
what do you need urllib for here in this file??

2022-03-23 16:41 UTC, joergfunger commented on probeye/definition/parameter.py
> +        # if (self._dim is not None) and (self._dim < 1):
not sure that that does, but either remove it, or uncomment

2022-03-23 16:41 UTC, joergfunger commented on probeye/inference/scipy/likelihood_models.py
> +            # in case of zero-residuals, a value of std_meas = 0 leads to a covariance
why is that the residuals and not the value of the function

2022-03-24 06:13 UTC, joergfunger requested changes
The ontology is quite complex, and I just started to look into the class definitions. From my point of view, it might be possible to remove some of the classes reducing complexity and allowing others to better understand the concepts.

2022-03-24 06:13 UTC, joergfunger commented on probeye/parameter_estimation_ontology.owl
> +        <obo:IAO_0000115 xml:lang="en">A data set that is an aggregate of data recordings all of which have in common that they have been measured in a single experiment.</obo:IAO_0000115>
from my point of view, it is really difficult to define objectively, what a single experiment is. If you perform a test series (an experiment) on 5 different materials and perform 3 different tests each and use 5 specimens extracted from one bulk material (of the 5 materials), what is the number of experiments?

2022-03-24 06:13 UTC, joergfunger commented on probeye/parameter_estimation_ontology.owl
> +    <owl:Class rdf:about="http://www.parameter_estimation_ontology.org#triple_constant">
the name is not very intuitive, and I'm also not sure why this is needed?

2022-03-24 06:13 UTC, joergfunger commented on probeye/parameter_estimation_ontology.owl
> +    <owl:Class rdf:about="http://www.parameter_estimation_ontology.org#uninformative_probability_density_function">
Does an uninformative pdf (as a term) really exist, or is it in the implementation rather a specific distribution with specials choices on the parameters to make it noninformative. (I guess the term is rather noninformative than uninformative)

2022-03-24 10:34 UTC, aklawonn commented on CHANGELOG.md
> +- Added an 'interface' submodule which contains a method 'export_to_rdf' that allows to print a defined problem to an rdf-file.
Done

2022-03-24 10:35 UTC, aklawonn commented on probeye/definition/inference_problem.py
> +import urllib
Old imports. Not needed anymore. Removed.

2022-03-24 10:36 UTC, aklawonn commented on probeye/definition/parameter.py
> +        # if (self._dim is not None) and (self._dim < 1):
Forgot to delete. It is deleted now.

2022-03-24 10:41 UTC, aklawonn commented on docs/examples/plot_correlation_1D.py
> +    domain="(0, +oo)",
True. But this is the definition part of the problem where computing methods should be avoided. Providing a specific function might also lead to problems between numpy.arrays and torch.tensors when used by the solvers. The advantage of intervals is their simplicity and therefore easier definition in the ontology. Most application cases should be covered by the interval-option.

2022-03-24 10:44 UTC, aklawonn commented on probeye/_setup_cfg.py
> +    # just for testing during CI
This file contains package-details like dependencies, version etc. This test covers the routine that checks if probeye still works with the latest versions of its dependencies.

2022-03-24 10:45 UTC, aklawonn commented on probeye/definition/parameter.py
> +    @staticmethod
See my comments above.

2022-03-24 10:57 UTC, aklawonn commented on probeye/inference/scipy/likelihood_models.py
> +            var = prms["std_model"] ** 2
No, the additive case. See [here](https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables).

2022-03-24 11:21 UTC, aklawonn commented on probeye/parameter_estimation_ontology.owl
> +    <owl:Class rdf:about="http://www.parameter_estimation_ontology.org#uninformative_probability_density_function">
It's an own thing. The term "uninformative" is used for example [here](https://en.wikipedia.org/wiki/Prior_probability).

2022-03-25 05:07 UTC, joergfunger commented on probeye/parameter_estimation_ontology.owl
> +    <owl:Class rdf:about="http://www.parameter_estimation_ontology.org#uninformative_probability_density_function">
The term is used in the literature, but at the end it is always a specific distribution behind it. IMO when creating the distribution, there could be a class that creates a non-informative distribution (e.g. as an argument), the return value should however be the precise distribution that has been choosen. (Otherwise the description is not reproducible)

2022-03-25 05:17 UTC, joergfunger commented on docs/examples/plot_correlation_1D.py
> +    domain="(0, +oo)",
There are some applications, where the constraints actually include more than one parameter (e.g. they should be inside circle, on one side of a hyperplane, ..). That is tricky to model and requires additional effort. If it is just a function of the parameter dict (that you yould also provide/document (e.g. https://stackoverflow.com/questions/40828921/parsing-a-string-input-into-a-lambda-function-python) as a string, it is much less code, much easier to extend by someone and thus easier to maintain. As for the pyro, we we should have a short discussion.

2022-03-25 05:25 UTC, joergfunger commented on probeye/inference/scipy/likelihood_models.py
> +            var = prms["std_model"] ** 2
so what is that std['model'] not sure that I understand that. I thought in the current implementation, the model uncertainty is zero. What exactly is that test for a the model std to be positive this should never be negative (I mean by definition)

2022-03-25 09:06 UTC, aklawonn commented on docs/examples/plot_correlation_1D.py
> +    domain="(0, +oo)",
I think this can be treated as an extension that is mostly independent from this PR. I opened a new issue #73 for that feature.

2022-03-25 09:10 UTC, aklawonn commented on probeye/inference/scipy/likelihood_models.py
> +            var = prms["std_model"] ** 2
The model error is meant here as the error between the model response and the corresponding experimental data. A more elaborate name is the "model prediction error". The checks have been defined before parameter domains have been introduced, because it was possible that the sampler were proposing negative values for std-parameter, which would then lead to an error.

2022-03-25 09:15 UTC, aklawonn commented on probeye/parameter_estimation_ontology.owl
> +    <owl:Class rdf:about="http://www.parameter_estimation_ontology.org#uninformative_probability_density_function">
So the uninformative prior is only relevant for maximum likelihood fits. An uninformative prior is equivalent with no prior defined. When performing a maximum likelihood fit, the user does not have to specify a prior. Internally, this is handled as an uninformative prior.

2022-03-25 12:17 UTC, joergfunger commented on probeye/inference/scipy/likelihood_models.py
> +            var = prms["std_model"] ** 2
what are std_model and std_measurement?

2022-03-25 12:21 UTC, joergfunger commented on probeye/parameter_estimation_ontology.owl
> +    <owl:Class rdf:about="http://www.parameter_estimation_ontology.org#uninformative_probability_density_function">
I would not fully agree. If you perform maximum likelihood, the prior is not used at all, i.e. it should not matter what distribution you are using. If you perform a full Bayesian approach, you have to specify a prior with a distribution function. There are different options discussed in literature, but they all have an underlying (flat) distribution that in particular depends on the scaling of the variable (so what could be considered a non-informative prior of a parameter x, it might not be a non-informative prior for a variable scaled by some factor e.g. y=1e6-6 x  (e.g. when changing from Pa to MPa).

2022-05-05 12:46 UTC, closed without merging