Dynesty solver
BAMresearch/probeye pull request #58
Opened 2021-11-30 08:24 UTC by TTitscher

2021-11-30 09:09 UTC, joergfunger requested changes
I'm somehow confused with the title and the section dynesty suggesting a nested sampling procedure whereas the implementation uses emcee as a MCMC sampler?

2021-11-30 09:12 UTC, TTitscher commented on tests/unit_tests/inference/dynesty_/test_solver.py
> +        # for mean, mean_true\
>This pull request is still a work in progress
Draft pull requests cannot be merged.

I opened that pull request only to let people know, I am working on it, in case someone else implements a dynesty solver. So nothing is finished -- not even started yet. :)

2021-12-01 08:55 UTC, aklawonn commented
Hi Thomas, thanks a lot for setting up the dynesty-solver so quickly! It looks pretty good to me. The only things I just added were some `run_dynesty` arguments in the integration tests which were missing, and I did the version increase from 1.0.14 to 1.0.15

2021-12-01 09:03 UTC, aklawonn approved these changes

2021-12-01 10:15 UTC, joergfunger requested changes
Great work, just a couple of potential improvements or questions from my side.

2021-12-01 10:15 UTC, joergfunger commented on probeye/inference/dynesty_/solver.py
> +        weights = np.exp(sampler.results.logwt - sampler.results.logz[-1])
So is that an additional plot routine extraction routine that resamples the output into the standard unweighted space? That also means that the results plotted are not fully the results obtained in the sampler, right?

2021-12-01 10:15 UTC, joergfunger commented on tests/unit_tests/inference/dynesty_/test_solver.py
> +        dynesty_solver.run_dynesty("static", nlive=50)
Shouldn't we use the dynamic version as "standard". At least from the literature is seems to yield more accurate results than the static version.

2021-12-01 10:15 UTC, joergfunger commented on tests/unit_tests/inference/dynesty_/test_solver.py
> +
The main feature of the nested sampling approach is to compute the evidence, could we use that for the analytical example where the evidence is known (in VB I guess) to have that as a test case here as well?

2021-12-01 10:28 UTC, TTitscher commented on tests/unit_tests/inference/dynesty_/test_solver.py
> +        dynesty_solver.run_dynesty("static", nlive=50)
The default method in the `DynestySolver.run` is indeed "dynamic". In this test, however, it runs for several minutes vs only seconds in "static" mode. Maybe I find a way to tweak the arguments of the "dynamic" mode to speed it up.

2021-12-01 10:31 UTC, TTitscher commented on tests/unit_tests/inference/dynesty_/test_solver.py
> +
IMO we should check, if dynesty is implemented correctly (another story), but only if our wrapper uses dynesty correctly. For this, I'd argue that it is enough to (roughly) check the means.

2021-12-01 10:34 UTC, TTitscher commented on probeye/inference/dynesty_/solver.py
> +        weights = np.exp(sampler.results.logwt - sampler.results.logz[-1])
The probeye post-processing (currently??) relies on arviz.InferenceData which does not support weights. So I see no other way rather ran this `resample_equal` method. The full (weighted) results are still accessible in the `raw_results` member for users that do not want to use the probeye post-processing.

2021-12-01 10:39 UTC, TTitscher commented on probeye/inference/dynesty_/solver.py
> +            The vector of ppfs for each prior distribution at theta.
I fixed the naming. Its the quantiles, so the output of the ppf.

2021-12-01 10:46 UTC, TTitscher commented on probeye/inference/dynesty_/solver.py
> +                mvn_ppf = norm.ppf(q=x, loc=loc, scale=np.diagonal(scale))
scipy.stats.multivariate_normal has no `ppf`, which makes sense as a (e.g.) 2D MVN would have a circle/ellipse as a quantile. 

But I checked the [dynesty documentation](https://dynesty.readthedocs.io/en/latest/quickstart.html#example-non-uniform-priors) and they provide another solution for the prior transform... I'll look into that. Thanks!

2021-12-01 14:56 UTC, joergfunger commented on probeye/inference/dynesty_/solver.py
> +        weights = np.exp(sampler.results.logwt - sampler.results.logz[-1])
OK, maybe just add some link where this resampling is discussed so that people interested in this know where to start, but otherwise I totally agree.

2021-12-01 14:57 UTC, joergfunger commented on tests/unit_tests/inference/dynesty_/test_solver.py
> +
But how do we extract the model evidence (in case that is of interest to someone)?

2021-12-01 15:22 UTC, TTitscher commented on tests/unit_tests/inference/dynesty_/test_solver.py
> +
Ok, we now log the evidence [here](https://github.com/BAMresearch/probeye/pull/58/commits/669a15ff33099219d1550b269c1c1d72b054bd48#diff-07bccec89d5b89bfd486d23f61f3808db0a0a0d89909f5a0ebcef27113337a39R210)

2021-12-01 16:19 UTC, joergfunger commented on tests/unit_tests/inference/dynesty_/test_solver.py
> +
Maybe that should not be part of the discussion in this pull request, but this feature (computing the model evidence based on the free energy in VB) would be computed also in other inference engines. Thus, it might be an option to include this (e.g. by extending the arviz class) to store this result (in case it is computed). But as mentioned, maybe this is a different issue.

2021-12-02 09:25 UTC, joergfunger approved these changes

2021-12-02 09:27 UTC, merged